# Tests to write
# 1) make sure no duplicate latitudes and longitude generated by chance

# Check errors
test_that("errors when input dates are in the wrong format", {
  expect_error(daily(start_date = "wrong format"),
               "start_date must be in YYYY-MM-DD format")
})


