# test_that("multiplication works", {
#   expect_equal(2 * 2, 4)
# })

# Tests to write
# 1) make sure no duplicate latitudes and longitude generated by chance


# Expect messages about locations_key
test_that("messages work when a location key already exists", {
  expect_error(sample_df(start_date = "wrong format"),
               "Start date must be in YYYY-MM-DD format.")
})


